"""ลายเซ็นต้องอยู่ในที่ที่ผู้ใช้เห็น ไม่ใช่แค่ในไฟล์ที่ลบทิ้งได้บรรทัดเดียว

เคสจริง 2026-08-20: มีคนเอา repo ไปพัฒนาต่อโดยไม่ให้เครดิต · LMDS เป็น proprietary
(ไม่ได้ให้สิทธิ์ fork เลย ต่างจาก LiteGate ที่เป็น MIT) — ประกาศจึงต้องอ่านง่ายและอยู่ติดตัว
โปรแกรม
"""

from pathlib import Path

from lmds.cli import banner

ROOT = Path(__file__).resolve().parents[1]


def test_attribution_has_one_source_of_truth():
    assert banner.AUTHOR == "neronain"
    assert "neronain.minidev" in banner.AUTHOR_URL
    assert banner.PRODUCT == "Local Model Deploy Studio"
    assert "Proprietary" in banner.LICENSE_NOTE
    # CREDIT ประกอบจากค่าข้างบน ไม่ใช่สตริงที่ก๊อปมาซ้ำ
    assert banner.AUTHOR in banner.CREDIT and banner.PRODUCT in banner.CREDIT


def test_version_endpoint_carries_it():
    api = (ROOT / "src/lmds/web/api.py").read_text(encoding="utf-8")
    for field in ('"author"', '"author_url"', '"product"', '"license"'):
        assert field in api, field


def test_console_shows_a_credit_footer():
    page = (ROOT / "src/lmds/web/static/index.html").read_text(encoding="utf-8")
    assert 'id="lmds-credit"' in page
    assert "#lmds-credit" in page, "footer ที่ไม่มีสไตล์ = footer ที่ไม่มีใครเห็น"
    # ค่ามาจากเซิร์ฟเวอร์ ถอดออกฝั่งนั้นแล้ว footer โล่งทันที — เป็นสัญญาณที่มองเห็น
    assert "d.author" in page


def test_generated_bundles_carry_it():
    """bundle ถูกส่งต่อไปเครื่องลูกค้า — เป็นจุดที่ลายเซ็นเดินทางไกลที่สุด"""
    templates = ROOT / "src/lmds/generator/templates"
    readme = (templates / "README.md.j2").read_text(encoding="utf-8")
    assert "neronain" in readme
    for controller in templates.glob("*controller.sh.j2"):
        assert "neronain" in controller.read_text(encoding="utf-8"), controller.name


def test_licence_and_notice_ship_with_the_code():
    licence = (ROOT / "LICENSE").read_text(encoding="utf-8")
    assert "neronain" in licence and "All rights reserved" in licence
    notice = (ROOT / "NOTICE").read_text(encoding="utf-8")
    assert "PROPRIETARY" in notice
    # ต้องบอกด้วยว่า bundle ที่ generate ออกมาเป็นของผู้ใช้ ไม่ใช่ห้ามทุกอย่าง
    assert "Bundles generated by LMDS" in notice
