"""Fleet หลายเครื่อง — hub เครื่องเดียวคุม node อื่นผ่าน SSH

ต่างจาก stacked (หลายเครื่อง = โมเดลเดียว) ตรงที่แต่ละ node เป็นอิสระต่อกัน
node ล่มหนึ่งเครื่องไม่กระทบเครื่องอื่น
"""

from .cluster import (
    MIN_STACK_GBPS,
    check_cluster_ip,
    link_warning,
    cluster_groups,
    cluster_note,
    connected_subset,
    connected_subsets,
    fabric_links,
    link_network,
    machine_identity,
    networks_of,
    parallelism_note,
    shared_fabric,
    stack_ready,
    suggest_cluster_ip,
    tensor_parallel_fits,
)
from .registry import (
    Node,
    NodeError,
    add,
    find,
    in_saved_order,
    load,
    nodes_file,
    remove,
    save,
    status_from_probe,
    suggest_name,
    update,
    validate_cluster_ip,
)
from .ssh import (
    explain_install_failure,
    install_script,
    run_privileged,
    push_file,
    stream,
    check_login,
    ensure_key,
    install_key,
    install_lmds,
    key_path,
    ownership_steps,
    probe,
    public_key_path,
    run,
)

__all__ = [
    "add",
    "check_cluster_ip",
    "link_warning",
    "check_login",
    "cluster_groups",
    "cluster_note",
    "connected_subset",
    "connected_subsets",
    "ensure_key",
    "fabric_links",
    "link_network",
    "machine_identity",
    "networks_of",
    "parallelism_note",
    "shared_fabric",
    "tensor_parallel_fits",
    "find",
    "in_saved_order",
    "install_key",
    "install_lmds",
    "install_script",
    "explain_install_failure",
    "key_path",
    "load",
    "MIN_STACK_GBPS",
    "Node",
    "NodeError",
    "nodes_file",
    "ownership_steps",
    "probe",
    "public_key_path",
    "push_file",
    "stream",
    "remove",
    "run",
    "run_privileged",
    "save",
    "stack_ready",
    "status_from_probe",
    "suggest_cluster_ip",
    "suggest_name",
    "update",
    "validate_cluster_ip",
]
